const data = [
  {
    cat: "Financial Services",
    name: "JPMorgan",
    value: 807,
    icon: "./img/jpmorgan.png",
    desc: "See how far your thinking can go.",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=1067%2C1068&geoId=103644278&keywords=software&location=United%20States",
    company: "Company Homepage",
    companyUrl: "https://careers.jpmorgan.com/us/en/home"
  },
  {
    cat: "Education",
    name: "UCSF",
    value: 248,
    icon: "./img/ucsf.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=3028%2C3029&geoId=103644278&keywords=software&location=United%20States",
    company: "Company Homepage",
    companyUrl: "https://www.ucsf.edu/about/working-ucsf"
  },
  {
    cat: "Education",
    name: "UC Berkeley",
    value: 130,
    icon: "./img/berkeley.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=2517&geoId=103644278&keywords=software&location=United%20States",
    company: "Company Homepage",
    companyUrl: "https://career.berkeley.edu/"
  },
  {
    cat: "Education",
    name: "UC Davis",
    value: 178,
    icon: "./img/ucdavis.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=2840%2C2842%2C2844&geoId=103644278&keywords=software&location=United%20States",
    company: "Company Homepage",
    companyUrl: "https://www.ucdavis.edu/jobs/"
  },
  {
    cat: "Tech",
    name: "Google",
    value: 1036,
    icon: "./img/google.png",
    desc: 'Software Engineer',
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=1441&geoId=103644278&keywords=software&location=United%20States",
    company: "Company Homepage",
    companyUrl: "https://careers.google.com/"
  },
  {
    cat: "Tech",
    name: "Salesforce",
    value: 1355,
    icon: "./img/salesforce.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=3185&geoId=103644278&keywords=software&location=United%20States",
    company: "Company Homepage",
    companyUrl: "https://www.salesforce.com/company/careers/"
  },
  {
    cat: "Financial Services",
    name: "Goldman Sachs",
    value: 375,
    icon: "./img/goldman.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=1382&geoId=103644278&keywords=software&location=United%20States",
    company: "Company Homepage",
    companyUrl: "https://www.goldmansachs.com/careers/"
  },
  {
    cat: "Tech",
    name: "Samsung",
    value: 239,
    icon: "./img/samsung.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=1753%2C1447520%2C3781124&geoId=103644278&keywords=software&location=United%20States",
    company: "Company Homepage",
    companyUrl: "https://www.samsung.com/us/careers/"
  },
  {
    cat: "Biotech",
    name: "Amgen",
    value: 168,
    icon: "./img/amgen.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=2068&geoId=103644278&keywords=software&location=United%20States",
    company: "Company Homepage",
    companyUrl: "https://careers.amgen.com/"
  },
  {
    cat: "Financial Services",
    name: "Capital One",
    value: 622,
    icon: "./img/capitalone.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=1419&geoId=103644278&keywords=software&location=United%20States",
    company: "Company Homepage",
    companyUrl: "https://www.capitalonecareers.com/"
  },
  {
    cat: "Education",
    name: "App Academy",
    value: 2,
    icon: "./img/aa.png",
    desc: "Instructor",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=3113247&geoId=103644278&keywords=software&location=United%20States",
    company: "Company Homepage",
    companyUrl: "https://jobs.lever.co/appacademy/"
  },
  {
    cat: "Tech",
    name: "Microsoft",
    value: 3225,
    icon: "./img/microsoft.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=1035&geoId=103644278&keywords=software&location=United%20States",
    company: "Company Homepage",
    companyUrl: "https://careers.microsoft.com/us/en/"
  },
  {
    cat: "Tech",
    name: "Apple",
    value: 1983,
    icon: "./img/apple.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=162479&geoId=103644278&keywords=software&location=United%20States",
    company: "Company Homepage",
    companyUrl: "https://www.apple.com/jobs/us/"
  },
  {
    cat: "Retail",
    name: "Nordstrom",
    value: 161,
    icon: "./img/nordstrom.png",
    desc: "Frontend Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=3379&keywords=software",
    company: "Company Homepage",
    companyUrl: "https://careers.nordstrom.com/"
  },
  {
    cat: "Philanthropy",
    name: "Bill & Melinda Gates Foundation",
    value: 5,
    icon: "./img/billgates.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=8736&keywords=software",
    company: "Company Homepage",
    companyUrl: "https://www.gatesfoundation.org/careers"
  },
  {
    cat: "Automotive",
    name: "Tesla",
    value: 553,
    icon: "./img/tesla.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=15564&keywords=software",
    company: "Company Homepage",
    companyUrl: "https://www.tesla.com/careers"
  },
  {
    cat: "Financial Services", 
    name: "American Express",
    value: 183,
    icon: "./img/amex.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=1277&keywords=software",
    company: "Company Homepage",
    companyUrl: "https://careers.americanexpress.com/"
  },
  {
    cat: "Financial Services",
    name: "Visa",
    value: 297,
    icon: "./img/visa.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=2190&keywords=software",
    company: "Company Homepage",
    companyUrl: "https://usa.visa.com/careers.html"
  },
  {
    cat: "Tech",
    name: "Facebook",
    value: 1072,
    icon: "./img/fb.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=10667&keywords=software",
    company: "Company Homepage",
    companyUrl: "https://www.facebook.com/careers/"
  },
  {
    cat: "Tech",
    name: "Uber",
    value: 238,
    icon: "./img/uber.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=1815218&keywords=software",
    company: "Company Homepage",
    companyUrl: "https://www.uber.com/us/en/careers/"
  },
  {
    cat: "Tech",
    name: "Airbnb",
    value: 35,
    icon: "./img/airbnb.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=309694&keywords=software",
    company: "Company Homepage",
    companyUrl: "https://careers.airbnb.com/"
  }, 
  {
    cat: "Tech",
    name: "YouTube",
    value: 16,
    icon: "./img/youtube.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=16140%2C1747859%2C29004510&keywords=software",
    company: "Company Homepage",
    companyUrl: "https://www.youtube.com/jobs/"
  }, 
  {
    cat: "Retail",
    name: "McDonald's",
    value: 29,
    icon: "./img/mcdonalds.png",
    desc: "Software Engineer",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=2677&keywords=software",
    company: "Company Homepage",
    companyUrl: "https://careers.mcdonalds.com/main/"
  }, 
  {
    cat: "Retail",
    name: "Starbucks",
    value: 56,
    icon: "./img/starbucks.png",
    desc: "Inspire positive change in the world while you grow in your career and in your community.",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=2271&keywords=software",
    company: "Company Homepage",
    companyUrl: "https://www.starbucks.com/careers/"
  }, 
  {
    cat: "Airlines",
    name: "Southwest",
    value: 4,
    icon: "./img/southwest.png",
    desc: "Share your interests and preferences for a personalized experience.",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=4599&keywords=software",
    company: "Company Homepage",
    companyUrl: "https://careers.southwestair.com/"
  },
  {
    cat: "Aerospace",
    name: "Boeing",
    value: 555,
    icon: "./img/boeing.png",
    desc: "From the seabed to outer space, we are redefining the next generation.",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=1384&keywords=software",
    company: "Company Homepage",
    companyUrl: "https://jobs.boeing.com/"
  },
  {
    cat: "Tech",
    name: "Twitter",
    value: 244,
    icon: "./img/twitter.png",
    desc: "",
    link: "Apply Now",
    linkUrl: "https://www.linkedin.com/jobs/search/?f_C=96622&keywords=software",
    company: "Company Homepage",
    companyUrl: "https://careers.twitter.com/"
  },
  {
    cat: "Tech",
    name: "Adobe",
    value: 313,
    icon: "./img/adobe.png",
    desc: "",
    link: "Apply Now",
    linkUrl: "https://www.adobe.com/careers.html",
    company: "Company Homepage",
    companyUrl: "https://careers.adobe.com/"
  },

];

module.exports = data;